(in-package :cl-user)

(defpackage :cl-liballegro-nuklear
  (:documentation "CFFI wrapper for Nuklear IM GUI library, to be used with cl-liballegro.")
  (:nicknames #:nk)
  (:use :cl)
  (:export
   #:false
   #:true
   #:color
   #:colorf
   #:vec-2
   #:rect
   #:glyph
   #:handle
   #:image
   #:scroll
   #:heading
   #:button-behavior
   #:chart-type
   #:popup-type
   #:symbol-type
   #:keys
   #:buttons
   #:collapse-states
   #:show-states
   #:layout-format
   #:tree-type
   #:panel-flags
   #:widget-layout-states
   #:widget-states
   #:text-align
   #:text-alignment
   #:edit-flags
   #:edit-types
   #:edit-events
   #:style-colors
   #:style-cursor
   ;; Context
   #:init-default
   #:init-fixed
   #:init
   #:init-custom
   #:clear
   #:free
   ;; Input
   #:input-begin
   #:input-motion
   #:input-key
   #:input-button
   #:input-scroll
   #:input-char
   #:input-glyph
   #:input-unicode
   #:input-end
   ;; Window
   #:begin
   #:begin-titled
   #:end
   #:window-find
   #:window-get-bounds
   #:window-get-position
   #:window-get-size
   #:window-get-width
   #:window-get-height
   #:window-get-panel
   #:window-get-content-region
   #:window-get-content-region-min
   #:window-get-content-region-max
   #:window-get-content-region-size
   #:window-get-canvas
   #:window-get-scroll
   #:window-has-focus
   #:window-is-hovered
   #:window-is-collapsed
   #:window-is-closed
   #:window-is-hidden
   #:window-is-active
   #:window-is-any-hovered
   #:item-is-any-active
   #:window-set-bounds
   #:window-set-position
   #:window-set-size
   #:window-set-focus
   #:window-set-scroll
   #:window-close
   #:window-collapse
   #:window-collapse-if
   #:window-show
   #:window-show-if
   ;; Layout
   #:layout-set-min-row-height
   #:layout-reset-min-row-height
   #:layout-widget-bounds
   #:layout-ratio-from-pixel
   #:layout-row-dynamic
   #:layout-row-static
   #:layout-row-begin
   #:layout-row-push
   #:layout-row-end
   #:layout-row
   #:layout-row-template-begin
   #:layout-row-template-push-dynamic
   #:layout-row-template-push-variable
   #:layout-row-template-push-static
   #:layout-row-template-end
   #:layout-space-begin
   #:layout-space-push
   #:layout-space-end
   #:layout-space-bounds
   #:layout-space-to-screen
   #:layout-space-to-local
   #:layout-space-rect-to-screen
   #:layout-space-rect-to-local
   ;; Groups
   #:group-begin
   #:group-begin-titled
   #:group-end
   #:group-scrolled-offset-begin
   #:group-scrolled-begin
   #:group-scrolled-end
   #:group-get-scroll
   #:group-set-scroll
   ;; Tree
   #:tree-push
   #:tree-push-hashed
   #:tree-image-push-hashed
   #:tree-pop
   #:tree-state-push
   #:tree-state-image-push
   #:tree-state-pop
   ;; List view
   #:list-view-begin
   #:list-view-end
   ;; Widget
   #:widget
   #:widget-fitting
   #:widget-bounds
   #:widget-position
   #:widget-size
   #:widget-width
   #:widget-height
   #:widget-is-hovered
   #:widget-is-mouse-clicked
   #:widget-has-mouse-click-down
   #:spacing
   ;; Text
   #:text
   #:text-colored
   #:text-wrap
   #:text-wrap-colored
   #:label
   #:label-colored
   #:label-wrap
   #:label-colored-wrap
   #:image
   #:image-color
   ;; Button
   #:button-text
   #:button-label
   #:button-color
   #:button-symbol
   #:button-image
   #:button-symbol-label
   #:button-symbol-text
   #:button-image-label
   #:button-image-text
   #:button-text-styled
   #:button-label-styled
   #:button-symbol-styled
   #:button-image-styled
   #:button-symbol-text-styled
   #:button-symbol-label-styled
   #:button-image-label-styled
   #:button-image-text-styled
   #:button-set-behavior
   #:button-push-behavior
   #:button-pop-behavior
   ;; Checkbox
   #:check-label
   #:check-text
   #:check-flags-label
   #:check-flags-text
   #:checkbox-label
   #:checkbox-text
   #:checkbox-flags-label
   #:checkbox-flags-text
   ;; Radio button
   #:radio-label
   #:radio-text
   #:option-label
   #:option-text
   ;; Selectable
   #:selectable-label
   #:selectable-text
   #:selectable-image-label
   #:selectable-image-text
   #:selectable-symbol-label
   #:selectable-symbol-text
   #:select-label
   #:select-text
   #:select-image-label
   #:select-image-text
   #:select-symbol-label
   #:select-symbol-text
   ;; Slider
   #:slide-float
   #:slide-int
   #:slider-float
   #:slider-int
   ;; Progressbar
   #:progress
   #:prog-
   ;; #:prog
   ;; Color picker
   #:colorf nk-color-picker
   #:color-pick
   ;; Properties
   #:property-int
   #:property-float
   #:property-double
   #:propertyi
   #:propertyf
   #:propertyd
   ;; Text edit
   #:edit-string
   #:edit-string-zero-terminated
   #:edit-buffer
   #:edit-focus
   #:edit-unfocus
   ;; Chart
   #:chart-begin
   #:chart-begin-colored
   #:chart-add-slot
   #:chart-add-slot-colored
   #:chart-push
   #:chart-push-slot
   #:chart-end
   #:plot
   #:plot-function
   ;; Popup
   #:popup-begin
   #:popup-close
   #:popup-end
   #:popup-get-scroll
   #:popup-set-scroll
   ;; Combobox
   #:combo
   #:combo-separator
   #:combo-string
   #:combo-callback
   #:combobox
   #:combobox-string
   #:combobox-separator
   #:combobox-callback
   ;; Abstract combox
   #:combo-begin-text
   #:combo-begin-label
   #:combo-begin-color
   #:combo-begin-symbol
   #:combo-begin-symbol-label
   #:combo-begin-symbol-text
   #:combo-begin-image
   #:combo-begin-image-label
   #:combo-begin-image-text
   #:combo-item-label
   #:combo-item-text
   #:combo-item-image-label
   #:combo-item-image-text
   #:combo-item-symbol-label
   #:combo-item-symbol-text
   #:combo-close
   #:combo-end
   ;; Contextual
   #:contextual-begin
   #:contextual-item-text
   #:contextual-item-label
   #:contextual-item-image-label
   #:contextual-item-image-text
   #:contextual-item-symbol-label
   #:contextual-item-symbol-text
   #:contextual-close
   #:contextual-end
   ;; Tooltip
   #:tooltip
   #:tooltip-begin
   #:tooltip-end
   ;; Menu
   #:menubar-begin
   #:menubar-end
   #:menu-begin-text
   #:menu-begin-label
   #:menu-begin-image
   #:menu-begin-image-text
   #:menu-begin-image-label
   #:menu-begin-symbol
   #:menu-begin-symbol-text
   #:menu-begin-symbol-label
   #:menu-item-text
   #:menu-item-label
   #:menu-item-image-label
   #:menu-item-image-text
   #:menu-item-symbol-text
   #:menu-item-symbol-label
   #:menu-close
   #:menu-end
   ;; Style
   #:style-default
   #:style-from-table
   #:style-load-cursor
   #:style-load-all-cursors
   #:style-get-color-by-name
   #:style-set-font
   #:style-set-cursor
   #:style-show-cursor
   #:style-hide-cursor
   #:style-push-font
   #:style-push-float
   #:style-push-vec2
   #:style-push-style-item
   #:style-push-flags
   #:style-push-color
   #:style-pop-font
   #:style-pop-float
   #:style-pop-vec2
   #:style-pop-style-item
   #:style-pop-flags
   #:style-pop-color
   ;; Color
   #:rgb
   #:rgb-iv
   #:rgb-bv
   #:rgb-f
   #:rgb-fv
   #:rgb-cf
   #:rgb-hex
   #:rgba
   #:rgba-u32
   #:rgba-iv
   #:rgba-bv
   #:rgba-f
   #:rgba-fv
   #:rgba-cf
   #:rgba-hex
   #:hsva-colorf
   #:hsva-colorfv
   #:colorf-hsva-f
   #:colorf-hsva-fv
   #:hsv
   #:hsv-iv
   #:hsv-bv
   #:hsv-f
   #:hsv-fv
   #:hsva
   #:hsva-iv
   #:hsva-bv
   #:hsva-f
   #:hsva-fv
   #:color-f
   #:color-fv
   #:color-cf
   #:color-d
   #:color-dv
   #:color-u32
   #:color-hex-rgba
   #:color-hex-rgb
   #:color-hsv-i
   #:color-hsv-b
   #:color-hsv-iv
   #:color-hsv-bv
   #:color-hsv-f
   #:color-hsv-fv
   #:color-hsva-i
   #:color-hsva-b
   #:color-hsva-iv
   #:color-hsva-bv
   #:color-hsva-f
   #:color-hsva-fv
   ;; Image
   #:handle-ptr
   #:handle-id
   #:image-handle
   #:image-ptr
   #:image-id
   #:image-is-subimage
   #:subimage-ptr
   #:subimage-id
   #:subimage-handle
   ;; Math
   #:murmur-hash
   #:triangle-from-direction
   #:vec2i
   #:vec2v
   #:vec2iv
   #:get-null-rect
   #:recti
   #:recta
   #:rectv
   #:rectiv
   #:rect-pos
   #:rect-size
   ;; String
   #:strfilter
   #:strmatch-fuzzy-string
   #:strmatch-fuzzy-text
   ;; UTF-8
   #:utf-decode
   #:utf-encode
   #:utf-len
   #:utf-at
   ;; Text editor
   #:filter-default
   #:filter-ascii
   #:filter-float
   #:filter-decimal
   #:filter-hex
   #:filter-oct
   #:filter-binary
   #:textedit-init-default
   #:textedit-init
   #:textedit-init-fixed
   #:textedit-free
   #:textedit-text
   #:textedit-delete
   #:textedit-delete-selection
   #:textedit-select-all
   #:textedit-cut
   #:textedit-paste
   #:textedit-undo
   #:textedit-redo
   ;; Drawing
   #:stroke-line
   #:stroke-curve
   #:stroke-rect
   #:stroke-circle
   #:stroke-arc
   #:stroke-triangle
   #:stroke-polyline
   #:stroke-polygon
   #:fill-rect
   #:fill-rect-multi-color
   #:fill-circle
   #:fill-arc
   #:fill-triangle
   #:fill-polygon
   #:draw-image
   #:draw-text
   #:push-scissor
   #:push-custom
   ;; Input
   #:input-has-mouse-click
   #:input-has-mouse-click-in-rect
   #:input-has-mouse-click-down-in-rect
   #:input-is-mouse-click-in-rect
   #:input-is-mouse-click-down-in-rect
   #:input-any-mouse-click-in-rect
   #:input-is-mouse-prev-hovering-rect
   #:input-is-mouse-hovering-rect
   #:input-mouse-clicked
   #:input-is-mouse-down
   #:input-is-mouse-pressed
   #:input-is-mouse-released
   #:input-is-key-pressed
   #:input-is-key-released
   #:input-is-key-down
   ;; GUI
   #:style-item-image
   #:style-item-color
   #:style-item-hide
   ;; Allegro backend
   #:allegro-init
   #:allegro-handle-event
   #:allegro-shutdown
   #:allegro-render
   #:allegro-create-image
   #:allegro-del-image
   #:allegro-font-create-from-file
   #:allegro-font-del
   #:allegro-font-set-font
   ;; Helpers
   #:flags))
